### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by mazipan** [fendy3002/QzStringTools#2]
Request buat web demo donk om @fendy3002 kalo ada.

**Comment by fendy3002** [comment]
Download aja, ada panduan instalasinya di readme.

Kalau tidak ngerti boleh tanya2

**Comment by mazipan** [comment]
Maksudnya biar bisa jadi web tools gitu, semacam json formatter online.
Soalnya hal2 kaya gini kadang butuh nya gak terduga dan biasanya sih orang lebih pengen cepet jadi prefer online tools.
But nice tools om.👍👍👍

**Comment by fendy3002** [comment]
Oh itu nanti ya, memang arahnya mau ke sana. Pakai github page saja

**Comment by fendy3002** [comment]
Online page: https://fendy3002.github.io/qzstring/index.html
